### ISSUE TITLE
Reduce Pokémon acceleration on indeterminate progress bar

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#11]
**Current behaviour (optional)**

When the progress bar is in indeterminate mode, the position is updated using a `velocity`. We accelerate (increase velocity) by 1 every time it is repainted. 

**Description of the desired feature (required)**

I think this is too fast of an acceleration, as the Pokémon seems to really zoom across the bar sometimes when it is smaller. However, if we don't accelerate at all, it takes a _really_ long time to get across on larger progress bars. We should reduce the acceleration.

**Why this feature would be valuable (optional)**

**How to implement this feature (optional)**

We could change the velocity to a `double`, and increment by 0.5 (or some other number, dependent on how it looks) instead of by 1. Then when we add it to the `pos`, we just take the floor value. We should introduce constants for `initialVelocity` and `acceleration` to make it easier to tweak these values.

**Additional information or context (optional)**

See [PokemonProgressBarUi:207](https://github.com/kagof/intellij-pokemon-progress/blob/a32d4a2b3d24bac537b2768a529039d0f2cfe0a9/src/main/java/com/kagof/intellij/plugins/pokeprogress/PokemonProgressBarUi.java#L207).

**Comment by VaibhaveS** [comment]
Hey can i work on this issue, also i see the label "Hacktoberfest" so does this mean i can work on this issue from 1st october onwards?

**Comment by kagof** [comment]
Hi @VaibhaveS, you're very welcome to work on this issue! I will assign it to you. You can work on it whenever - feel free to start it now, or if you want to hold off until October so you get the Hacktoberfest, that's absolutely fine too.

I think the ticket here has a decent amount of  information in it, but don't hesitate to ask for guidance if you need it!

**Comment by kagof** [comment]
Hi @VaibhaveS have you had any luck with this? :)

**Comment by kagof** [comment]
@VaibhaveS I've unassigned you and assigned myself, however if you'd still like to work on this feel free to let me know and I'll reassign you :)
