### ISSUE TITLE
Add Gen III Starters

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#16]
**Pokémon Name/Number (required):**

* Treecko (252) (Grass)
* Sceptile (254) (Grass)
* Torchic (255) (Fire)
* Blaziken (257) (Fire/Fighting)
* Mudkip (258) (Water)
* Swampert (260) (Water/Ground)

**Pokémon Sprite(s) (optional):**

* See https://www.pokencyclopedia.info/en/index.php?id=sprites/overworlds/o-r_hgss

**I've checked that these Pokémon have not already been requested or added in an upcoming release (required):**

* yes

**Comment by jayaganeshkumar** [comment]
@kagof  Can you explain what we have to do here?

**Comment by kagof** [comment]
@jayaganeshkumar there are some steps outlined in the [Contributing guidelines](https://github.com/kagof/intellij-pokemon-progress/blob/master/CONTRIBUTING.md).

However it would be good if I wrote up a solid step-by-step guide on how to do this. I'll try to get something like that written up to make first time contributions a bit easier

**Comment by Paola351** [comment]
Hi! Can i work on this?

**Comment by kagof** [comment]
Hi @Paola351 , I'd like to give @jayaganeshkumar a chance to claim this first. However, if they aren't interested, it is all yours :)

**Comment by jayaganeshkumar** [comment]
@kagof  Hey, sorry for the late reply. Do I need to update the code in pokemon.java and in the readme for this issue? If yes, I am ready.

**Comment by kagof** [comment]
Hi @jayaganeshkumar, the code in Pokemon.java will need to be updated, updating the Readme is optional but appreciated (there is a test class that helps you generate the lines).

In addition, sprites will need to be created for each of the new Pokémon. Is that all OK with you?

**Comment by jayaganeshkumar** [comment]
What are negative numbers in pokemon java where we update the pokemon details?

**Comment by jayaganeshkumar** [comment]
@kagof hey man, I have some exams these days and I request you to assign this issue to others. Sorry for delaying the replies.
