### ISSUE TITLE
Add Gen IV Starters

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#17]
**Pokémon Name/Number (required):**

* Turtwig (387) (Grass)
* Torterra (389) (Grass/Ground)
* Chimchar (390) (Fire)
* Infernape (392) (Fire/Fighting)
* Piplup (393) (Water)
* Empoleon (395) (Water/Steel)

**Pokémon Sprite(s) (optional):**

* See https://www.pokencyclopedia.info/en/index.php?id=sprites/overworlds/o-r_hgss

**I've checked that these Pokémon have not already been requested or added in an upcoming release (required):**

* yes

**Comment by Paola351** [comment]
Hi! can i work on this?

**Comment by kagof** [comment]
@Paola351 I've assigned it to you :) 

Please take a look at the [Contributing Guidelines](https://github.com/kagof/intellij-pokemon-progress/blob/master/CONTRIBUTING.md), which has some hints on how to get started. If you have any issues, feel free to ask for help!

**Comment by Paola351** [comment]
@kagof everything is ready for a review I think
