### ISSUE TITLE
Add Gen II Legendary/Mythical Pokémon

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#18]
**Pokémon Name/Number (required):**

* Raikou (243) (Electric)
* Entei (244) (Fire)
* Suicune (245) (Water)
* Lugia (249) (Psychic/Flying)
* Ho-Oh (250) (Fire/Flying)
* Celebi (251) (Psychic/Grass)

**Pokémon Sprite(s) (optional):**

* see https://www.pokencyclopedia.info/en/index.php?id=sprites/overworlds/o-r_hgss

**I've checked that these Pokémon have not already been requested or added in an upcoming release (required):**

* yes

**Comment by marcodenisi** [comment]
Hello there, can I work on this one?

**Comment by kagof** [comment]
@marcodenisi absolutely, I'll assign this to you. 

Note: there are some steps outlined in the [Contributing guidelines](https://github.com/kagof/intellij-pokemon-progress/blob/master/CONTRIBUTING.md) on how to proceed.

I'm realizing it would be good if I wrote up a solid step-by-step guide on how to add new Pokémon. I'll try to get something like that written up at some point in the near-ish future to make first time contributions a bit easier. In the mean time, feel free to let me know if you need help along the way.

**Comment by marcodenisi** [comment]
Hi @kagof, I've pushed what I hope fixes your comments. Let me know if there's anything else I can do.

**Comment by kagof** [comment]
resolved in 1.3.0 via #22
