### ISSUE TITLE
Add Gen V Starters

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#19]
**Pokémon Name/Number (required):**

* Snivy (495) (Grass)
* Serperior (497) (Grass)
* Tepig (498) (Fire)
* Emboar (500) (Fire/Fighting)
* Oshawott (501) (Water)
* Samurott (503) (Water)

**Pokémon Sprite(s) (optional):**

This one is a bit trickier. Heart Gold/Soul Silver doesn't have sprites for these Pokémon. Looking at the Bulbagarden archives there's some possible options, but I'm not sure how good it'll look (eg, https://archives.bulbagarden.net/wiki/Category:Snivy). The menu sprite is 32x32, which is a good size for us, but it is more of an idle sprite than a walking sprite, and I'm not sure that really fits aesthetically. Maybe someone somewhere has created walking overworld sprites for this gen?

**I've checked that these Pokémon have not already been requested or added in an upcoming release (required):**

* yes

**Comment by Paola351** [comment]
Can I work on it? :) Is it valid for the hacktoberfest?

**Comment by kagof** [comment]
I think this one requires some discussion/investigation before any real work can be done on it - specifically, I'm not sure where to get the sprites for this generation. If you have any ideas for that, feel free to let me know!

The only real option I've seen so far is to use the idle menu sprites, but I'm not thrilled with that idea aesthetically - we've managed to have walking sprites for every other Pokémon so I don't think it would look great.

**Comment by Paola351** [comment]
> I think this one requires some discussion/investigation before any real work can be done on it - specifically, I'm not sure where to get the sprites for this generation. If you have any ideas for that, feel free to let me know!
> 
> The only real option I've seen so far is to use the idle menu sprites, but I'm not thrilled with that idea aesthetically - we've managed to have walking sprites for every other Pokémon so I don't think it would look great.

I found [this](https://www.spriters-resource.com/download/34007/) for Snivy... What do you think about that?
