### ISSUE TITLE
Could you add another pokemon?

### ISSUE THREAD

**Issue by gray-kim** [kagof/intellij-pokemon-progress#2]
Hi~
I like your plugin because I'm big fan of pokemon.

I wonder if you add another pokemon.
I want Gyarados, Slowpoke, Koffing.!
I think 1st generation pokemon is more cute than other generation! :)

Thanks for making this awesome plugin.

**Comment by jigrid** [comment]
Hello! +_+//

your plugin  So CUTE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

this plugin make me happy ♥

Thanks~!

**Comment by kagof** [comment]
I should be able to do that :)

Thanks for the kind words!
