### ISSUE TITLE
Add GEN III Mythical Pokémon

### ISSUE THREAD

**Issue by Paola351** [kagof/intellij-pokemon-progress#20]
Pokémon Name/Number (required):

Kyogre (382) (Water)
Groudon (383) (Ground)
Rayquaza (384) (Dragon/Flying)
Jirachi (385) (Steel/Psychic)
Deoxys (386) (Psychic)

Pokémon Sprite(s) (optional):

see https://www.pokencyclopedia.info/en/index.php?id=sprites/overworlds/o-r_hgss

I've checked that these Pokémon have not already been requested or added in an upcoming release (required):

yes

**Comment by Paola351** [comment]
Hi! I would like to work on this :D Sorry if I opened it directly

**Comment by kagof** [comment]
Hi @Paola351, that's great! I'd be thrilled to get these ones added as well. Assigning this to you, and giving it the hacktoberfest label.

You know the drill already: see [contributing](https://github.com/kagof/intellij-pokemon-progress/blob/master/CONTRIBUTING.md) for some hints on how to get started, and feel free to ask for help!

**Comment by Paola351** [comment]
thx :D i would like to take even the other open issue and even some more to add others legends and starters :D what do you think about that? @kagof

**Comment by Paola351** [comment]
I added the first pull request, let me know what do you think about it :D

**Comment by Paola351** [comment]
@kagof are you there?

**Comment by Paola351** [comment]
@kagof there's only 8 days left to review this, please :'(

**Comment by kagof** [comment]
resolved in 1.3.0
