### ISSUE TITLE
Getting IDE Fatal Errors

### ISSUE THREAD

**Issue by ShadowChild** [kagof/intellij-pokemon-progress#44]
**Description of the bug & expected behaviour (required)**

After installing the plugin, I constantly get a notification in the bottom saying "IDE error occurred", which brings me to the page saying it caught an exception in your plugin.
the exception is in this link https://pastebin.com/qNn4BEzy

**Environment Info (required)**

* **OS:** Windows 10 20H2
* **JetBrains Product:** eg. IntelliJ Ultimate
* **JetBrains Product Version:** eg. 2021.1.EAP
* **Plugin Version:** eg. 1.4.2

**Steps to reproduce (optional)**

Install plugin, and do anything to bring up the progress bar

**Additional context or information (optional)**

eg. It only happens when it is raining

**Comment by kagof** [comment]
Interesting, this doesn't seem to happen with ≤ 2020.3, so likely something that they've changed/removed in 2021.1. I haven't played around with the EAP version at all yet; I'll try to see if I can pinpoint the issue & fix it this weekend.

Thanks for the bug report!

**Comment by ShadowChild** [comment]
No worries, just wanted to bring it to your attention.

**Comment by kagof** [comment]
Thanks @ShadowChild :) This has been resolved in the upcoming 1.5.0 release!
