### ISSUE TITLE
Chosen Pokemon is randomised but the tooltip doesn't change

### ISSUE THREAD

**Issue by yopox** [kagof/intellij-pokemon-progress#56]
**Description of the bug & expected behaviour**

1. Start an inspection
2. Open and close 'Background Tasks' popup multiple times

I would expect the pokemon to stay the same or the tooltip to update accordingly.

![Kapture 2021-10-15 at 13 19 32](https://user-images.githubusercontent.com/8440079/137479425-2e581408-a5b7-44de-88cd-0105c0f609b2.gif)

**Environment Info**

IntelliJ IDEA 2021.3 EAP (Ultimate Edition)
Build #IU-213.5062, built on October 14, 2021
IntelliJ IDEA EAP User
Expiration date: November 13, 2021
Runtime version: 11.0.12+7-b1729.1 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12

Non-Bundled Plugins:
    com.kagof.pokeprogress (1.6.0)

Kotlin: 213-1.5.10-release-945-IJ5062

**Comment by kagof** [comment]
Interesting, thank you for the very detailed report! I'll look into this.

**Comment by kagof** [comment]
fixed in #60, which will be included in the next release (1.7.0, to be released soon)
