### ISSUE TITLE
Add a way to select / deselect whole generations in settings

### ISSUE THREAD

**Issue by chylex** [kagof/intellij-pokemon-progress#57]
**Current behaviour (optional)**

Currently you can only toggle individual Pokémon, or all Pokémon at once.

**Description of the desired feature (required)**

There could be a checkbox next to every "Generation &lt;X&gt;" label, which affects all Pokémon in that generation.

**Why this feature would be valuable (optional)**

Saves hands :clap: 

**How to implement this feature (optional)**

IntelliJ SDK has a `ThreeStateCheckBox` which would probably be the most appropriate UI element for this.

I'm happy to make a PR for this.

**Comment by kagof** [comment]
Hi @chylex, this is a great idea, feel free to raise a PR for this!

**Comment by chylex** [comment]
Forgot to link the issue in commit message, so linking here: https://github.com/kagof/intellij-pokemon-progress/pull/58

**Comment by kagof** [comment]
Done in #58, to be included in the next release (1.7.0, to be released soon)
