### ISSUE TITLE
Possibility of having multiple themes for the gradient

### ISSUE THREAD

**Issue by chylex** [kagof/intellij-pokemon-progress#59]
**Current behaviour (optional)**

There are some options to change the look, but none that affect the color gradient.

**Description of the desired feature (required)**

Since there are many possibilities of how the gradient could look, there could be a drop-down with a few predefined themes.

**Why this feature would be valuable (optional)**

Purely personal choice of aesthetics.

**Additional information or context (optional)**

I experimented with what looks I would prefer personally, and came up with a "Dark Flat" theme that uses the dark color of the types:

![obrazek](https://user-images.githubusercontent.com/3685160/142129205-d5903d75-9b9f-4446-96f4-26041cdcfb91.png)

Another option could be just "Flat" that uses the middle color:

![obrazek](https://user-images.githubusercontent.com/3685160/142130155-a42d0567-0559-4249-8bcf-37e65a49bcf5.png)

or "Light Flat":

![obrazek](https://user-images.githubusercontent.com/3685160/142129940-7e2c42d6-86de-46d7-9eab-ebd54ec7144a.png)

**Comment by kagof** [comment]
Hi @chylex, I'd be OK with adding these options. Are you willing to open a PR to add these options? 

A couple of notes, I'd like the current gradient to remain the default. Likely a good place to add the drop-down would be in the `checkboxPanel` (along with a sensible rename 😅) unless you can think of a better spot.

**Comment by chylex** [comment]
Sure, I can add a drop-down with the current style and my 3 new styles, and submit a PR.

When I was experimenting with this, I also thought about adding a way to quickly cycle through a bunch of different Pokémon, to see how each style looks with different types - what do you think about a button in the Settings that randomly changes currently shown Pokémon? If that sounds good, I could include it in the PR, or open a new issue for it. I'm not sure what'd be a good spot for it though.

**Comment by kagof** [comment]
Could that maybe be added to or replace the preview panel on the configuration page?

![Screenshot Preview](https://user-images.githubusercontent.com/17553493/149638908-fe2c0c2f-09d3-4dc7-9cb9-ac95ab5027c9.png)

It could be a "refresh" or "randomize" button on that panel.

Perhaps it would be better to do that as a separate PR if it isn't too much extra work, just to keep this ticket pared down to only what is relevant to it.

**Comment by chylex** [comment]
Yea, I'll implement it separately and open a new issue with screenshots of how it looks before I PR it.

**Comment by kagof** [comment]
Perfect, thank you!

**Comment by kagof** [comment]
added in 1.7.0
