### ISSUE TITLE
Broken unicode text when building on Windows systems

### ISSUE THREAD

**Issue by chylex** [kagof/intellij-pokemon-progress#62]
**Description of the bug & expected behaviour (required)**

On Windows, the Java compiler assumes a file encoding "appropriate" for the user's language settings instead of UTF-8. If the plugin is built on Windows, the generated JAR file will have broken `Pokémon` strings.

![obrazek](https://user-images.githubusercontent.com/3685160/149664849-9c2b6c21-4432-4959-8d1e-72868e2dae14.png)

The fix is to set Java compiler to use UTF-8. I will make a PR for this in a bit.

**Environment Info (required)**

* **OS:** Windows
* **JetBrains Product:** Any
* **JetBrains Product Version:** Any
* **Plugin Version:** Any

**Comment by kagof** [comment]
Fixed in 1.7.0
