### ISSUE TITLE
Not work in 2023 version

### ISSUE THREAD

**Issue by rino3390** [kagof/intellij-pokemon-progress#87]
**Description of the bug & expected behaviour (required)**

After updating to version 2023, the Pokemon bar is not displayed.
However, if I change the theme and then change it back, it can be displayed normally.
I've already raised this issue with JetBrains officially, but they suggested I contact the plugin author.
I really like this plugin and hope that it can be supported in the 2023 version.

**Environment Info (required)**

* **OS:** Window
* **JetBrains Product:** Rider
* **JetBrains Product Version:** 2023
* **Plugin Version:** 2.1.1

**Steps to reproduce (optional)**

1. open IDE
2. not display

**Additional context or information (optional)**

If I change the theme and then change it back, it can be displayed normally, not display when restart IDE.

**Comment by kagof** [comment]
This appears to be the first report of #89, which I plan to look into soon
