### ISSUE TITLE
It does not work when I have only one Pokemon selected [Rider]

### ISSUE THREAD

**Issue by jasursadikov** [kagof/intellij-pokemon-progress#88]
The loader is not working with one Pokemon selected.
I have Rider and PyCharm Community Edition, it is working with PyCharm but it is does not work with Rider

![image](https://github.com/kagof/intellij-pokemon-progress/assets/14846427/ea3263d3-0faf-4b04-a0c6-91b5ea75e3cc)
![image](https://github.com/kagof/intellij-pokemon-progress/assets/14846427/e6b52c7e-d6fd-48e4-ae71-eba5fb8e19fc)

**Environment Info:**

* **OS:** ArchLinux  
![image](https://github.com/kagof/intellij-pokemon-progress/assets/14846427/2c05f9b2-703c-4ad7-82c4-1290db0430b2)
* **JetBrains Product:** Rider
* **JetBrains Product Version:** Rider: 2023.3.2
* **Plugin Version:** eg. 1.0.0
 
**Steps to reproduce**

1. Go to settings
2. Deselect all Pokemons
3. Select Jigglypuff 
4. Close settings
5. Enjoy default progress bar :crying_cat_face:

**Comment by jasursadikov** [comment]
I tried to uninstall but now it does not work completely. :(

**Comment by kagof** [comment]
Hi @jasursadikov, I've seen various reports of a similar issue on IntelliJ 2023.3.x, and can see something similar myself. I don't think it's related to the number of Pokémon selected, rather I think it is just an issue with the plugin's bootstrapping process. I'll be looking into this with ticket https://github.com/kagof/intellij-pokemon-progress/issues/89. As such I'm going to close this ticket as I think it was a bit of a red herring. 

However, if you still have reason to believe there's an issue specifically with selecting a single Pokémon, please do let me know!
