### ISSUE TITLE
Make chosen Pokémon configurable

### ISSUE THREAD

**Issue by kagof** [kagof/intellij-pokemon-progress#9]
**Current behaviour (optional)**

If a Pokémon is added, it is added. There is no way for a user to exclude a Pokémon that they don't like or think is ugly.

**Description of the desired feature (required)**

We could add an appearance configuration page for this app, which lets the user decide which Pokémon to include. By default, all would be included.

**Why this feature would be valuable (optional)**

As more and more Pokémon get added, it is more and more likely that people will come across one that they don't want to be included.

**How to implement this feature (optional)**

this is JetBrains' guide for making a plugin have settings https://jetbrains.org/intellij/sdk/docs/reference_guide/settings_guide.html

* we would need to add a settings page, with a list of all Pokémon that a user can enable/disable as they please. Ideally, this list should be generated at runtime not compile time, so we don't need to manually update it every time we add a new Pokémon.
* the state of these settings would have to be persisted
* We need to consider the case where the user turns off every Pokémon. What do we do here? Maybe just a bar that fills with the colour but no Pokémon? Maybe an Easter Egg, like Red or a Pokéball, or MissingNo? Maybe we just set the progress bar back to what it was before this plugin was loaded?

**Additional information or context (optional)**

**Comment by fbecker-complex** [comment]
Hi @kagof just stumbled over this thread while looking for a way to configure the used pokemon.
Could you add some instructions on how to do it, I can't seem to figure it out.

**Comment by kagof** [comment]
@fbecker-complex you're not the first person to ask about this; I think I should add to the README and the plug-in description.

But in the mean time for your reference, this setting can be found under Preferences > Appearance & Behaviour > Pokémon Progress

**Comment by fbecker-complex** [comment]
> @fbecker-complex you're not the first person to ask about this; I think I should add to the README and the plug-in description.
> 
> But in the mean time for your reference, this setting can be found under Preferences > Appearance & Behaviour > Pokémon Progress

Thanks for the quick reply!

Yes, I think that would be nice to help people like myself.
Now it works!

Great plugin, by the way 😉

**Comment by kagof** [comment]
Thanks very much! Glad you're enjoying it.
